name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js and corepack
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Setup pnpm
        run: corepack enable pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build Docs
        run: |
          cd docs
          pnpm install
          pnpm run build
          cd ..

      - name: Build REPL
        run: |
          cd repl
          pnpm install
          pnpm run build
          cd ..

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ # Specify the directory to publish

      - name: Copy docs build to root
        run: |
          mkdir -p docs
          cp -r docs/dist/* docs/

      - name: Copy repl build to root
        run: |
          mkdir -p repl
          cp -r repl/dist/* repl/
